export const trainData = [
	{
		trainNo: 107,
		trainName: "SWV-MAO-VLNK",
		SEQ: 1,
		Station Code: "SWV",
		Station Name: "SAWANTWADI R",
		Arrival time: "00:00:00",
		Departure Time: "10:25:00",
		Distance: 0,
		Source Station: "SWV",
		Source Station Name: "SAWANTWADI ROAD",
		Destination Station: "MAO",
		Destination Station Name: "MADGOAN JN."
	},
	{
		trainNo: 107,
		trainName: "SWV-MAO-VLNK",
		SEQ: 2,
		Station Code: "THVM",
		Station Name: "THIVIM",
		Arrival time: "11:06:00",
		Departure Time: "11:08:00",
		Distance: 32,
		Source Station: "SWV",
		Source Station Name: "SAWANTWADI ROAD",
		Destination Station: "MAO",
		Destination Station Name: "MADGOAN JN."
	},
	{
		trainNo: 107,
		trainName: "SWV-MAO-VLNK",
		SEQ: 3,
		Station Code: "KRMI",
		Station Name: "KARMALI",
		Arrival time: "11:28:00",
		Departure Time: "11:30:00",
		Distance: 49,
		Source Station: "SWV",
		Source Station Name: "SAWANTWADI ROAD",
		Destination Station: "MAO",
		Destination Station Name: "MADGOAN JN."
	},
	{
		trainNo: 107,
		trainName: "SWV-MAO-VLNK",
		SEQ: 4,
		Station Code: "MAO",
		Station Name: "MADGOAN JN.",
		Arrival time: "12:10:00",
		Departure Time: "00:00:00",
		Distance: 78,
		Source Station: "SWV",
		Source Station Name: "SAWANTWADI ROAD",
		Destination Station: "MAO",
		Destination Station Name: "MADGOAN JN."
	},
	{
		trainNo: 108,
		trainName: "VLNK-MAO-SWV",
		SEQ: 1,
		Station Code: "MAO",
		Station Name: "MADGOAN JN.",
		Arrival time: "00:00:00",
		Departure Time: "20:30:00",
		Distance: 0,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "SWV",
		Destination Station Name: "SAWANTWADI ROAD"
	},
	{
		trainNo: 108,
		trainName: "VLNK-MAO-SWV",
		SEQ: 2,
		Station Code: "KRMI",
		Station Name: "KARMALI",
		Arrival time: "21:04:00",
		Departure Time: "21:06:00",
		Distance: 33,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "SWV",
		Destination Station Name: "SAWANTWADI ROAD"
	},
	{
		trainNo: 108,
		trainName: "VLNK-MAO-SWV",
		SEQ: 3,
		Station Code: "THVM",
		Station Name: "THIVIM",
		Arrival time: "21:26:00",
		Departure Time: "21:28:00",
		Distance: 51,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "SWV",
		Destination Station Name: "SAWANTWADI ROAD"
	},
	{
		trainNo: 108,
		trainName: "VLNK-MAO-SWV",
		SEQ: 4,
		Station Code: "SWV",
		Station Name: "SAWANTWADI R",
		Arrival time: "22:25:00",
		Departure Time: "00:00:00",
		Distance: 83,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "SWV",
		Destination Station Name: "SAWANTWADI ROAD"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 1,
		Station Code: "MAO",
		Station Name: "MADGOAN JN.",
		Arrival time: "19:40:00",
		Departure Time: "19:40:00",
		Distance: 0,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 2,
		Station Code: "KRMI",
		Station Name: "KARMALI",
		Arrival time: "20:18:00",
		Departure Time: "20:20:00",
		Distance: 33,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 3,
		Station Code: "THVM",
		Station Name: "THIVIM",
		Arrival time: "20:40:00",
		Departure Time: "20:42:00",
		Distance: 51,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 4,
		Station Code: "SWV",
		Station Name: "SAWANTWADI R",
		Arrival time: "21:16:00",
		Departure Time: "21:18:00",
		Distance: 83,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 5,
		Station Code: "KUDL",
		Station Name: "KUDAL",
		Arrival time: "21:38:00",
		Departure Time: "21:40:00",
		Distance: 104,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 6,
		Station Code: "SNDD",
		Station Name: "SINDHU DURG",
		Arrival time: "21:54:00",
		Departure Time: "21:56:00",
		Distance: 114,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 7,
		Station Code: "KKW",
		Station Name: "KANKAVALI",
		Arrival time: "22:18:00",
		Departure Time: "22:20:00",
		Distance: 132,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 8,
		Station Code: "VBW",
		Station Name: "VAIBHAVWADI",
		Arrival time: "22:40:00",
		Departure Time: "22:42:00",
		Distance: 163,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 9,
		Station Code: "RAJP",
		Station Name: "RAJAPUR ROAD",
		Arrival time: "22:56:00",
		Departure Time: "22:58:00",
		Distance: 179,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 10,
		Station Code: "RN",
		Station Name: "RATNAGIRI",
		Arrival time: "23:52:00",
		Departure Time: "23:57:00",
		Distance: 244,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 11,
		Station Code: "SGR",
		Station Name: "SANGMESHWAR",
		Arrival time: "00:34:00",
		Departure Time: "00:36:00",
		Distance: 280,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 12,
		Station Code: "CHI",
		Station Name: "CHIPLUN",
		Arrival time: "01:10:00",
		Departure Time: "01:12:00",
		Distance: 322,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 13,
		Station Code: "KHED",
		Station Name: "KHED",
		Arrival time: "01:52:00",
		Departure Time: "01:54:00",
		Distance: 352,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 14,
		Station Code: "MNI",
		Station Name: "MANGAON",
		Arrival time: "04:00:00",
		Departure Time: "04:02:00",
		Distance: 422,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 15,
		Station Code: "ROHA",
		Station Name: "ROHA",
		Arrival time: "04:55:00",
		Departure Time: "05:00:00",
		Distance: 455,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 16,
		Station Code: "PNVL",
		Station Name: "PANVEL",
		Arrival time: "06:20:00",
		Departure Time: "06:25:00",
		Distance: 532,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 17,
		Station Code: "KJT",
		Station Name: "KARJAT",
		Arrival time: "07:40:00",
		Departure Time: "07:45:00",
		Distance: 560,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 18,
		Station Code: "LNL",
		Station Name: "LONAVLA",
		Arrival time: "08:30:00",
		Departure Time: "08:33:00",
		Distance: 588,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 19,
		Station Code: "PUNE",
		Station Name: "PUNE JN.",
		Arrival time: "10:30:00",
		Departure Time: "10:45:00",
		Distance: 652,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 20,
		Station Code: "STR",
		Station Name: "SATARA",
		Arrival time: "13:42:00",
		Departure Time: "13:45:00",
		Distance: 797,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 21,
		Station Code: "MRJ",
		Station Name: "MIRAJ JN.",
		Arrival time: "16:25:00",
		Departure Time: "16:35:00",
		Distance: 931,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 128,
		trainName: "MAO-KOP SPEC",
		SEQ: 22,
		Station Code: "KOP",
		Station Name: "CHHATRAPATI",
		Arrival time: "17:45:00",
		Departure Time: "17:45:00",
		Distance: 978,
		Source Station: "MAO",
		Source Station Name: "MADGOAN JN.",
		Destination Station: "KOP",
		Destination Station Name: "CHHATRAPATI SHAHU MAHARAJ TERMINUS"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 1,
		Station Code: "DSJ",
		Station Name: "DELHI-SAFDAR",
		Arrival time: "18:30:00",
		Departure Time: "18:30:00",
		Distance: 0,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 2,
		Station Code: "GADJ",
		Station Name: "GANDHINAGAR",
		Arrival time: "03:45:00",
		Departure Time: "07:45:00",
		Distance: 306,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 3,
		Station Code: "JP",
		Station Name: "JAIPUR JN.",
		Arrival time: "08:00:00",
		Departure Time: "11:55:00",
		Distance: 311,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 4,
		Station Code: "DPA",
		Station Name: "DURGAPURA",
		Arrival time: "18:00:00",
		Departure Time: "20:00:00",
		Distance: 318,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 5,
		Station Code: "SWM",
		Station Name: "SAWAI MADHOP",
		Arrival time: "04:45:00",
		Departure Time: "08:40:00",
		Distance: 442,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 6,
		Station Code: "COR",
		Station Name: "CHITTAURGARH",
		Arrival time: "00:05:00",
		Departure Time: "02:00:00",
		Distance: 707,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 7,
		Station Code: "UDZ",
		Station Name: "UDAIPUR CITY",
		Arrival time: "08:00:00",
		Departure Time: "11:00:00",
		Distance: 821,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 8,
		Station Code: "JSM",
		Station Name: "JAISALMER",
		Arrival time: "09:15:00",
		Departure Time: "13:00:00",
		Distance: 1660,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 9,
		Station Code: "MDB",
		Station Name: "MANDOR",
		Arrival time: "07:00:00",
		Departure Time: "10:50:00",
		Distance: 1951,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 10,
		Station Code: "FL",
		Station Name: "PHULERA JN.",
		Arrival time: "22:00:00",
		Departure Time: "22:55:00",
		Distance: 2213,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 11,
		Station Code: "BTE",
		Station Name: "BHARATPUR JN",
		Arrival time: "05:00:00",
		Departure Time: "08:45:00",
		Distance: 2455,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 12,
		Station Code: "IDH",
		Station Name: "IDGAH",
		Arrival time: "11:00:00",
		Departure Time: "11:30:00",
		Distance: 2507,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 13,
		Station Code: "AGC",
		Station Name: "AGRA CANTT",
		Arrival time: "19:00:00",
		Departure Time: "19:30:00",
		Distance: 2508,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 290,
		trainName: "PALACE ON WH",
		SEQ: 14,
		Station Code: "DSJ",
		Station Name: "DELHI-SAFDAR",
		Arrival time: "02:30:00",
		Departure Time: "02:30:00",
		Distance: 2694,
		Source Station: "DSJ",
		Source Station Name: "DELHI-SAFDAR JANG",
		Destination Station: "DSJ",
		Destination Station Name: "DELHI-SAFDAR JANG"
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 1,
		Station Code: "AWB",
		Station Name: "AURANGABAD",
		Arrival time: "21:30:00",
		Departure Time: "21:30:00",
		Distance: 0,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 2,
		Station Code: "MMR",
		Station Name: "MANMAD JN.",
		Arrival time: "01:20:00",
		Departure Time: "01:30:00",
		Distance: 131,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 3,
		Station Code: "BSL",
		Station Name: "BHUSAVAL JN.",
		Arrival time: "05:20:00",
		Departure Time: "05:30:00",
		Distance: 315,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 4,
		Station Code: "KNW",
		Station Name: "KHANDWA JN.",
		Arrival time: "07:30:00",
		Departure Time: "07:35:00",
		Distance: 438,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 5,
		Station Code: "JHS",
		Station Name: "JHANSI JN",
		Arrival time: "14:55:00",
		Departure Time: "15:05:00",
		Distance: 1003,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 6,
		Station Code: "CNB",
		Station Name: "KANPUR CENTR",
		Arrival time: "19:10:00",
		Departure Time: "19:15:00",
		Distance: 1221,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 7,
		Station Code: "LKO",
		Station Name: "LUCKNOW JN.",
		Arrival time: "23:50:00",
		Departure Time: "23:55:00",
		Distance: 1295,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 8,
		Station Code: "BBK",
		Station Name: "BARA BANKI J",
		Arrival time: "01:15:00",
		Departure Time: "01:20:00",
		Distance: 1323,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 9,
		Station Code: "AY",
		Station Name: "AYODHYA",
		Arrival time: "04:45:00",
		Departure Time: "04:50:00",
		Distance: 1430,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 10,
		Station Code: "SHG",
		Station Name: "SHAHGANJ JN.",
		Arrival time: "07:10:00",
		Departure Time: "07:15:00",
		Distance: 1527,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 11,
		Station Code: "JNU",
		Station Name: "JAUNPUR JN.",
		Arrival time: "08:00:00",
		Departure Time: "08:05:00",
		Distance: 1561,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 401,
		trainName: "BSB BHARATDA",
		SEQ: 12,
		Station Code: "BSB",
		Station Name: "VARANASI JN.",
		Arrival time: "10:00:00",
		Departure Time: "10:00:00",
		Distance: 1618,
		Source Station: "AWB",
		Source Station Name: "AURANGABAD",
		Destination Station: "BSB",
		Destination Station Name: "VARANASI JN."
	},
	{
		trainNo: 421,
		trainName: "LKO-SVDK FTR",
		SEQ: 1,
		Station Code: "LKO",
		Station Name: "LUCKNOW JN.",
		Arrival time: "23:00:00",
		Departure Time: "23:00:00",
		Distance: 0,
		Source Station: "LKO",
		Source Station Name: "LUCKNOW JN.",
		Destination Station: "SVDK",
		Destination Station Name: "SHRI MATA VAISHNO DEVI KATRA"
	},
	{
		trainNo: 421,
		trainName: "LKO-SVDK FTR",
		SEQ: 2,
		Station Code: "FGR",
		Station Name: "FATEHGARH",
		Arrival time: "03:03:00",
		Departure Time: "03:30:00",
		Distance: 207,
		Source Station: "LKO",
		Source Station Name: "LUCKNOW JN.",
		Destination Station: "SVDK",
		Destination Station Name: "SHRI MATA VAISHNO DEVI KATRA"
	},
	{
		trainNo: 421,
		trainName: "LKO-SVDK FTR",
		SEQ: 3,
		Station Code: "KSJ",
		Station Name: "KASGANJ JN.",
		Arrival time: "06:00:00",
		Departure Time: "06:30:00",
		Distance: 319,
		Source Station: "LKO",
		Source Station Name: "LUCKNOW JN.",
		Destination Station: "SVDK",
		Destination Station Name: "SHRI MATA VAISHNO DEVI KATRA"
	},
	{
		trainNo: 421,
		trainName: "LKO-SVDK FTR",
		SEQ: 4,
		Station Code: "BE",
		Station Name: "BAREILLY JN.",
		Arrival time: "09:42:00",
		Departure Time: "09:47:00",
		Distance: 456,
		Source Station: "LKO",
		Source Station Name: "LUCKNOW JN.",
		Destination Station: "SVDK",
		Destination Station Name: "SHRI MATA VAISHNO DEVI KATRA"
	},
	{
		trainNo: 421,
		trainName: "LKO-SVDK FTR",
		SEQ: 5,
		Station Code: "SVDK",
		Station Name: "SHRI MATA VA",
		Arrival time: "08:00:00",
		Departure Time: "08:00:00",
		Distance: 1276,
		Source Station: "LKO",
		Source Station Name: "LUCKNOW JN.",
		Destination Station: "SVDK",
		Destination Station Name: "SHRI MATA VAISHNO DEVI KATRA"
	},
	{
		trainNo: 422,
		trainName: "SVDK-LKO FTR",
		SEQ: 1,
		Station Code: "SVDK",
		Station Name: "SHRI MATA VA",
		Arrival time: "11:45:00",
		Departure Time: "11:45:00",
		Distance: 0,
		Source Station: "SVDK",
		Source Station Name: "SHRI MATA VAISHNO DEVI KATRA",
		Destination Station: "LKO",
		Destination Station Name: "LUCKNOW JN."
	},
	{
		trainNo: 422,
		trainName: "SVDK-LKO FTR",
		SEQ: 2,
		Station Code: "BE",
		Station Name: "BAREILLY JN.",
		Arrival time: "03:25:00",
		Departure Time: "03:30:00",
		Distance: 820,
		Source Station: "SVDK",
		Source Station Name: "SHRI MATA VAISHNO DEVI KATRA",
		Destination Station: "LKO",
		Destination Station Name: "LUCKNOW JN."
	},
	{
		trainNo: 422,
		trainName: "SVDK-LKO FTR",
		SEQ: 3,
		Station Code: "KSJ",
		Station Name: "KASGANJ JN.",
		Arrival time: "06:35:00",
		Departure Time: "07:05:00",
		Distance: 956,
		Source Station: "SVDK",
		Source Station Name: "SHRI MATA VAISHNO DEVI KATRA",
		Destination Station: "LKO",
		Destination Station Name: "LUCKNOW JN."
	},
	{
		trainNo: 422,
		trainName: "SVDK-LKO FTR",
		SEQ: 4,
		Station Code: "FGR",
		Station Name: "FATEHGARH",
		Arrival time: "09:30:00",
		Departure Time: "09:35:00",
		Distance: 1069,
		Source Station: "SVDK",
		Source Station Name: "SHRI MATA VAISHNO DEVI KATRA",
		Destination Station: "LKO",
		Destination Station Name: "LUCKNOW JN."
	},
	{
		trainNo: 422,
		trainName: "SVDK-LKO FTR",
		SEQ: 5,
		Station Code: "LKO",
		Station Name: "LUCKNOW JN.",
		Arrival time: "14:30:00",
		Departure Time: "14:30:00",
		Distance: 1277,
		Source Station: "SVDK",
		Source Station Name: "SHRI MATA VAISHNO DEVI KATRA",
		Destination Station: "LKO",
		Destination Station Name: "LUCKNOW JN."
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 1,
		Station Code: "SSA",
		Station Name: "SIRSA",
		Arrival time: "12:10:00",
		Departure Time: "12:10:00",
		Distance: 0,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 2,
		Station Code: "HSR",
		Station Name: "HISAR JN",
		Arrival time: "13:55:00",
		Departure Time: "14:25:00",
		Distance: 81,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 3,
		Station Code: "BNW",
		Station Name: "BHIWANI JN.",
		Arrival time: "15:55:00",
		Departure Time: "16:20:00",
		Distance: 141,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 4,
		Station Code: "ROK",
		Station Name: "ROHTAK JN.",
		Arrival time: "17:38:00",
		Departure Time: "17:40:00",
		Distance: 189,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 5,
		Station Code: "DSJ",
		Station Name: "DELHI-SAFDAR",
		Arrival time: "20:13:00",
		Departure Time: "20:15:00",
		Distance: 317,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 6,
		Station Code: "CNB",
		Station Name: "KANPUR CENTR",
		Arrival time: "05:30:00",
		Departure Time: "05:35:00",
		Distance: 762,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 7,
		Station Code: "MGS",
		Station Name: "MUGHAL SARAI",
		Arrival time: "12:40:00",
		Departure Time: "12:50:00",
		Distance: 1098,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 8,
		Station Code: "MGS",
		Station Name: "MUGHAL SARAI",
		Arrival time: "16:10:00",
		Departure Time: "16:20:00",
		Distance: 1513,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 9,
		Station Code: "CNB",
		Station Name: "KANPUR CENTR",
		Arrival time: "21:00:00",
		Departure Time: "21:05:00",
		Distance: 1850,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 10,
		Station Code: "DSJ",
		Station Name: "DELHI-SAFDAR",
		Arrival time: "07:13:00",
		Departure Time: "07:15:00",
		Distance: 2299,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 11,
		Station Code: "ROK",
		Station Name: "ROHTAK JN.",
		Arrival time: "09:43:00",
		Departure Time: "09:45:00",
		Distance: 2426,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 12,
		Station Code: "BNW",
		Station Name: "BHIWANI JN.",
		Arrival time: "11:05:00",
		Departure Time: "11:35:00",
		Distance: 2474,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 13,
		Station Code: "HSR",
		Station Name: "HISAR JN",
		Arrival time: "13:10:00",
		Departure Time: "13:40:00",
		Distance: 2534,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 477,
		trainName: "FTR TRAIN NO",
		SEQ: 14,
		Station Code: "SSA",
		Station Name: "SIRSA",
		Arrival time: "15:20:00",
		Departure Time: "15:20:00",
		Distance: 2616,
		Source Station: "SSA",
		Source Station Name: "SIRSA",
		Destination Station: "SSA",
		Destination Station Name: "SIRSA"
	},
	{
		trainNo: 502,
		trainName: "RJPB-UMB FTR",
		SEQ: 1,
		Station Code: "RJPB",
		Station Name: "RAJENDRANAGA",
		Arrival time: "10:30:00",
		Departure Time: "10:30:00",
		Distance: 0,
		Source Station: "RJPB",
		Source Station Name: "RAJENDRANAGAR TERMINAL",
		Destination Station: "UMB",
		Destination Station Name: "AMBALA CANTT JN"
	}
]