export const trainData = [
  {
    _id: "63d9f686cfbd8c7d6cf1792a",
    arrivalTime: "17:05:00",
    departureTime: "17:05:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "0",
    seq: "1",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "NDLS",
    stationName: "NEW DELHI",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf1792b",
    arrivalTime: "21:45:00",
    departureTime: "21:50:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "430",
    seq: "2",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "CNB",
    stationName: "KANPUR CENTR",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf1792c",
    arrivalTime: "01:55:00",
    departureTime: "02:05:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "777",
    seq: "3",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "MGS",
    stationName: "MUGHAL SARAI",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf1792d",
    arrivalTime: "03:58:00",
    departureTime: "04:01:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "981",
    seq: "4",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "GAYA",
    stationName: "GAYA JN.",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf1792e",
    arrivalTime: "05:19:00",
    departureTime: "05:21:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1057",
    seq: "5",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "KQR",
    stationName: "KODERMA",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf1792f",
    arrivalTime: "06:30:00",
    departureTime: "06:35:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1151",
    seq: "6",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "GMO",
    stationName: "NSC BOSE J G",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17930",
    arrivalTime: "07:35:00",
    departureTime: "07:40:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1183",
    seq: "7",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "BKSC",
    stationName: "BOKARO STEEL",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17931",
    arrivalTime: "10:35:00",
    departureTime: "10:40:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1339",
    seq: "8",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "TATA",
    stationName: "TATANAGAR JN",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17932",
    arrivalTime: "12:25:00",
    departureTime: "12:40:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1477",
    seq: "9",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "KGP",
    stationName: "KHARAGPUR",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17933",
    arrivalTime: "14:02:00",
    departureTime: "14:04:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1598",
    seq: "10",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "BLS",
    stationName: "BALASORE",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17934",
    arrivalTime: "15:12:00",
    departureTime: "15:14:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1660",
    seq: "11",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "BHC",
    stationName: "BHADRAKH",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17935",
    arrivalTime: "16:40:00",
    departureTime: "16:42:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1775",
    seq: "12",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "CTC",
    stationName: "CUTTACK JN.",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
  {
    _id: "63d9f686cfbd8c7d6cf17936",
    arrivalTime: "17:25:00",
    departureTime: "17:25:00",
    destinationStation: "BBS",
    destinationStationName: "BHUBANESWAR",
    distance: "1802",
    seq: "13",
    sourceStation: "NDLS",
    sourceStationName: "NEW DELHI",
    stationCode: "BBS",
    stationName: "BHUBANESWAR",
    trainName: "NDLS-BBS RAJ",
    trainNo: "22824",
  },
];
